name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - name: Install frontend dependencies
        run: bun install --frozen-lockfile --verbose
        working-directory: streamlit_wavesurfer/frontend

      - name: Build frontend
        run: bun run build
        working-directory: streamlit_wavesurfer/frontend

      - name: Install uv (GitHub-hosted)
        uses: astral-sh/setup-uv@v5

      - name: Build Python package
        run: uv build
        working-directory: streamlit_wavesurfer