name: CI

on:
  push:
    branches: [main]
    tags: ['v*']  # Trigger on version tags like v1.0.0
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || startsWith(github.ref, 'refs/heads/')
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install frontend dependencies
        run: bun install --frozen-lockfile --verbose
        working-directory: streamlit_wavesurfer/frontend

      - name: Build frontend
        run: bun run build
        working-directory: streamlit_wavesurfer/frontend

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Build Python package
        run: uv build

  publish:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install frontend dependencies
        run: bun install --frozen-lockfile --verbose
        working-directory: streamlit_wavesurfer/frontend

      - name: Build frontend
        run: bun run build
        working-directory: streamlit_wavesurfer/frontend

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Build Python package
        run: uv build

      - name: Publish Python package
        run: uv publish
