name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y unzip curl

      - uses: oven-sh/setup-bun@v2

      - name: Install frontend dependencies
        run: bun install --frozen-lockfile --verbose
        working-directory: streamlit_wavesurfer/frontend

      - name: Build frontend
        run: bun run build
        working-directory: streamlit_wavesurfer/frontend

      - name: Install uv (GitHub-hosted)
        if: ${{ !env.ACT }}
        uses: astral-sh/setup-uv@v5

      - name: Install uv (act/local)
        if: ${{ env.ACT }}
        run: |
          curl -sSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          # add uv to PATH
          export PATH="$HOME/.cargo/bin:$PATH"

      - name: Build Python package
        run: uv build
        working-directory: streamlit_wavesurfer