name: CI

on:
  push:
    branches: [main]
    tags: ['v*']  # Trigger on version tags like v1.0.0
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || startsWith(github.ref, 'refs/heads/')
    steps:
      - &checkout
        uses: actions/checkout@v3
      - &setup-bun
        uses: oven-sh/setup-bun@v2
      - &setup-uv
        uses: astral-sh/setup-uv@v5
      - &install-frontend
        name: Install frontend dependencies
        run: bun install --frozen-lockfile --verbose
        working-directory: streamlit_wavesurfer/frontend
      - &build-frontend
        name: Build frontend
        run: bun run build
        working-directory: streamlit_wavesurfer/frontend
      - &build-python
        name: Build Python package
        run: uv build

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: main
    steps:
      - *checkout
      - *setup-bun
      - *setup-uv
      - *install-frontend
      - *build-frontend
      - *build-python
      - name: Publish Python package
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}